---

- name: create leaf interface profile, its related interface-selector profile and associate it with the switch-profile.
  hosts: lab-apic
  connection: local
  gather_facts: no

  tasks:
      - name: create interface profile
        aci_interface_policy_leaf_profile:
                    host: "{{ ansible_host }}"
                    username: "{{ apic_username }}"
                    password: "{{ apic_password }}"
                    validate_certs: no
                    leaf_interface_profile: int-vpc-n5k

      - name: create interface selector under it and bind to policy group
        aci_access_port_to_interface_policy_leaf_profile:
                    host: "{{ ansible_host }}"
                    username: "{{ apic_username }}"
                    password: "{{ apic_password }}"
                    validate_certs: no
                    leaf_interface_profile: int-vpc-n5k
                    access_port_selector: int-sel-vpc-n5k
                    leaf_port_blk: 2
                    from_port: 7
                    to_port: 7
                    policy_group: vpc-n5k

      - name: associate the interface selector to the switch profile
        aci_interface_selector_to_switch_policy_leaf_profile:
                    host: "{{ ansible_host }}"
                    username: "{{ apic_username }}"
                    password: "{{ apic_password }}"
                    validate_certs: no
                    leaf_profile: Switch101-102_Profile
                    interface_selector: int-vpc-n5k


        


