---

- name: create a physical or l2 or l3 or fc domain and bind to vlanpool.
  hosts: lab-apic
  connection: local
  gather_facts: no

  tasks:
   - name: add a physical domain
     aci_domain:
      host: "{{ ansible_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: no
      domain: rhel-servers
      domain_type: phys

   - name: bind domain to vlanpool
     aci_domain_to_vlan_pool:
      host: "{{ ansible_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: no
      domain: rhel-servers
      domain_type: phys
      pool: vlan-pool-rhel-servers
      pool_allocation_mode: static

