---

- name: bind AEP to some Domain
  hosts: lab-apic
  connection: local
  gather_facts: no

  tasks:
  - name: binding between AEP and domains
    aci_aep_to_domain:
      host: "{{ ansible_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: no
      aep: aep-tenant2
      domain: l2-tenant2
      domain_type: l2dom
