---

- name: create a l3out (external routed networks)
  hosts: lab-apic
  connection: local
  gather_facts: no

  tasks:
   - name: add a l3out
     aci_l3out:
       host: "{{ ansible_host }}"
       username: "{{ apic_username }}"
       password: "{{ apic_password }}"
       validate_certs: no
       tenant: tenant2
       name: l3out-ospf-n5k
       description: "Test L3OUT created by Ansible"
       domain: vpc-n5k
       vrf: tenant2
       l3protocol: ospf
       route_control: export

   - name: modify ospf attribures using the aci_rest module. The aci_l3out module only creates the top-level l3out object. For the rest, pls use aci_rest.
     aci_rest: 
       host: "{{ ansible_host }}"
       username: "{{ apic_username }}"
       password: "{{ apic_password }}"
       validate_certs: no
       path: /api/node/mo/uni/tn-tenant2/out-l3out-ospf-n5k/ospfExtP.json?
       method: post
       content: 
         ospfExtP:
                 attributes: 
                   areaId: 2
                   areaType: regular
              


   - name: create a custom ospf interface policy
     aci_interface_policy_ospf:
        host: "{{ ansible_host }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"
        validate_certs: no
        tenant: tenant2
        network_type: bcast
        ospf: ospf-bcast-intf-policy
        controls: mtu-ignore
